[tool.poetry]
name = "jd-py-aula-03"
version = "0.1.0"
description = ""
authors = ["apontevinicius <apontevinicius@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
